[project]
name = "hgvs-ext"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pydantic>=2.10.6",
    "python-decouple>=3.8",
    "python-dotenv>=1.0.1",
]
